export const ELEMENT_FAMILIES = {
	en: [
		'Alkali metals',
		'Alkaline earth metals',
		'Transition series',
		'Post-transition series',
		'Metalloids',
		'Non-metals',
		'Noble gases',
		'Lanthanides',
		'Actinides'
	],
	es: [
		'Metales alcalinos',
		'Metales alcalinotérreos',
		'Serie de transición',
		'Serie posterior a la transición',
		'Metaloides',
		'No-metales',
		'Gases nobles',
		'Lantánidos',
		'Actínidos'
	],
	fr: [
		'Métaux alcalins',
		'Métaux alcalino-terreux',
		'Série Transitions',
		'Série Post-Transition',
		'Métalloïdes',
		'Non-métaux',
		'Gaz nobles',
		'Lanthanides',
		'Actinides'
	],
	it: [
		'Metalli alcalini',
		'Metalli alcalino-terrosi',
		'Serie di transizione',
		"Serie post-transizione",
		'Metalloidi',
		'Non-metalli',
		'Gas nobili',
		'Lantanidi',
		'Attinidi'
	]
};

export const ELEMENTS = [
	{ family: 0, symbol: 'Li', label: 'Lithium' },
	{ family: 0, symbol: 'Na', label: 'Sodium' },
	{ family: 0, symbol: 'K', label: 'Potassium' },
	{ family: 0, symbol: 'Rb', label: 'Rubidium' },
	{ family: 0, symbol: 'Cs', label: 'Cesium' },
	{ family: 0, symbol: 'Fr', label: 'Francium' },
	{ family: 1, symbol: 'Be', label: 'Beryllium' },
	{ family: 1, symbol: 'Mg', label: 'Magnesium' },
	{ family: 1, symbol: 'Ca', label: 'Calcium' },
	{ family: 1, symbol: 'Sr', label: 'Strontium' },
	{ family: 1, symbol: 'Ba', label: 'Barium' },
	{ family: 1, symbol: 'Ra', label: 'Radium' },
	{ family: 2, symbol: 'Sc', label: 'Scandium'},
	{ family: 2, symbol: 'Ti', label: 'Titanium'},
	{ family: 2, symbol: 'V', label: 'Vanadium'},
	{ family: 2, symbol: 'Cr', label: 'Chromium'},
	{ family: 2, symbol: 'Mn', label: 'Manganese'},
	{ family: 2, symbol: 'Fe', label: 'Iron'},
	{ family: 2, symbol: 'Co', label: 'Cobalt'},
	{ family: 2, symbol: 'Ni', label: 'Nickel'},
	{ family: 2, symbol: 'Cu', label: 'Copper'},
	{ family: 2, symbol: 'Zn', label: 'Zn'},
	{ family: 2, symbol: 'Y', label: 'Yttrium'},
	{ family: 2, symbol: 'Zr', label: 'Zirconium'},
	{ family: 2, symbol: 'Nb', label: 'Niobium'},
	{ family: 2, symbol: 'Mo', label: 'Molybdenum'},
	{ family: 2, symbol: 'Tc', label: 'Technetium'},
	{ family: 2, symbol: 'Ru', label: 'Ruthenium'},
	{ family: 2, symbol: 'Rh', label: 'Rhodium'},
	{ family: 2, symbol: 'Pd', label: 'Palladium'},
	{ family: 2, symbol: 'Ag', label: 'Silver'},
	{ family: 2, symbol: 'Cd', label: 'Cadmium'},
	{ family: 2, symbol: 'La', label: 'Lanthanum'},
	{ family: 2, symbol: 'Hf', label: 'Hafnium'},
	{ family: 2, symbol: 'Ta', label: 'Tantalum'},
	{ family: 2, symbol: 'W', label: 'Tungsten'},
	{ family: 2, symbol: 'Re', label: 'Rhenium'},
	{ family: 2, symbol: 'Os', label: 'Osmium'},
	{ family: 2, symbol: 'Ir', label: 'Iridium'},
	{ family: 2, symbol: 'Pt', label: 'Platinum'},
	{ family: 2, symbol: 'Au', label: 'Gold'},
	{ family: 2, symbol: 'Hg', label: 'Mercury'},
	{ family: 2, symbol: 'Ac', label: 'Actinium'},
	{ family: 2, symbol: 'Rf', label: 'Rutherfordium'},
	{ family: 2, symbol: 'Db', label: 'Dubnium'},
	{ family: 2, symbol: 'Sg', label: 'Seaborgium'},
	{ family: 2, symbol: 'Bh', label: 'Bohrium'},
	{ family: 2, symbol: 'Hs', label: 'Hassium'},
	{ family: 2, symbol: 'Mt', label: 'Meitnerium'},
	{ family: 2, symbol: 'Ds', label: 'Darmstadtium'},
	{ family: 2, symbol: 'Rg', label: 'Roentgenium'},
	{ family: 2, symbol: 'Cn', label: 'Copernicium'},
	{ family: 3, symbol: 'Al', label: 'Aluminum'},
	{ family: 3, symbol: 'Ga', label: 'Gallium'},
	{ family: 3, symbol: 'In', label: 'Indium'},
	{ family: 3, symbol: 'Sn', label: 'Tin'},
	{ family: 3, symbol: 'Tl', label: 'Thallium'},
	{ family: 3, symbol: 'Pb', label: 'Lead'},
	{ family: 3, symbol: 'Bi', label: 'Bismuth'},
	{ family: 3, symbol: 'Nh', label: 'Nihonium'},
	{ family: 3, symbol: 'Fl', label: 'Flerovium'},
	{ family: 3, symbol: 'Mc', label: 'Moscovium'},
	{ family: 3, symbol: 'Lv', label: 'Livermorium'},
	{ family: 4, symbol: 'B', label: 'Boron'},
	{ family: 4, symbol: 'Si', label: 'Silicon'},
	{ family: 4, symbol: 'Ge', label: 'Germanium'},
	{ family: 4, symbol: 'As', label: 'Arsenic'},
	{ family: 4, symbol: 'Sb', label: 'Antimony'},
	{ family: 4, symbol: 'Te', label: 'Tellurium'},
	{ family: 4, symbol: 'Po', label: 'Polonium'},
	{ family: 5, symbol: 'H', label: 'Hydrogen' },
	{ family: 5, symbol: 'C', label: 'Carbon' },
	{ family: 5, symbol: 'N', label: 'Nitrogen' },
	{ family: 5, symbol: 'O', label: 'Oxygen' },
	{ family: 5, symbol: 'F', label: 'Fluorine' },
	{ family: 5, symbol: 'P', label: 'Phosphorus' },
	{ family: 5, symbol: 'S', label: 'Sulfur' },
	{ family: 5, symbol: 'Cl', label: 'Chlorine'},
	{ family: 5, symbol: 'Se', label: 'Selenium'},
	{ family: 5, symbol: 'Br', label: 'Bromine'},
	{ family: 5, symbol: 'I', label: 'Iodine'},
	{ family: 5, symbol: 'At', label: 'Astatine'},
	{ family: 5, symbol: 'Ts', label: 'Tennessine'},
	{ family: 6, symbol: 'He', label: 'Helium'},
	{ family: 6, symbol: 'Ne', label: 'Neon'},
	{ family: 6, symbol: 'Ar', label: 'Argon'},
	{ family: 6, symbol: 'Kr', label: 'Krypton'},
	{ family: 6, symbol: 'Xe', label: 'Xenon'},
	{ family: 6, symbol: 'Rn', label: 'Radon'},
	{ family: 6, symbol: 'Og', label: 'Oganesson'},
	{ family: 7, symbol: 'Ce', label: 'Cerium' },
	{ family: 7, symbol: 'Pr', label: 'Praseodymium' },
	{ family: 7, symbol: 'Nd', label: 'Neodymium' },
	{ family: 7, symbol: 'Pm', label: 'Promethium' },
	{ family: 7, symbol: 'Sm', label: 'Samarium' },
	{ family: 7, symbol: 'Eu', label: 'Europium' },
	{ family: 7, symbol: 'Gd', label: 'Gadolinium' },
	{ family: 7, symbol: 'Tb', label: 'Terbium' },
	{ family: 7, symbol: 'Dy', label: 'Dysprosium' },
	{ family: 7, symbol: 'Ho', label: 'Holmium' },
	{ family: 7, symbol: 'Er', label: 'Erbium' },
	{ family: 7, symbol: 'Tm', label: 'Thulium' },
	{ family: 7, symbol: 'Yb', label: 'Ytterbium' },
	{ family: 7, symbol: 'Lu', label: 'Lutetium' },
	{ family: 8, symbol: 'Th', label: 'Thorium' },
	{ family: 8, symbol: 'Pa', label: 'Protactinium' },
	{ family: 8, symbol: 'U', label: 'Uranium' },
	{ family: 8, symbol: 'Np', label: 'Neptunium' },
	{ family: 8, symbol: 'Pu', label: 'Plutonium' },
	{ family: 8, symbol: 'Am', label: 'Americium' },
	{ family: 8, symbol: 'Cm', label: 'Curium' },
	{ family: 8, symbol: 'Bk', label: 'Berkellium' },
	{ family: 8, symbol: 'Cf', label: 'Californium' },
	{ family: 8, symbol: 'Es', label: 'Einsteinium' },
	{ family: 8, symbol: 'Fm', label: 'Fermium' },
	{ family: 8, symbol: 'Md', label: 'Mendelevium' },
	{ family: 8, symbol: 'No', label: 'Nobelium' },
	{ family: 8, symbol: 'Lr', label: 'Lawrencium' }
];

export const PERIODIC_TABLE_DATA = {
	ELEMENT_FAMILIES,
	ELEMENTS
};

export default PERIODIC_TABLE_DATA;
