export const TEXT_MAP = {
  de: {
    heading: 'Um',
    content: 'Mein Name ist Dr. David Partyka und ich habe Crystal Search gegründet. Obwohl ich mehrere Jahre als Chemiker ausgebildet war, sogar an einer Spitzenuniversität promovierte und über 20 Artikel veröffentlichte, wechselte ich zur Webentwicklung, nachdem das letzte Ingenieurbüro, für das ich gearbeitet hatte (das sich stark auf Chemie konzentrierte), im Jahr 2011 zusammenbrach. Ich habe diesen beruflichen Wechsel vollzogen, um bessere Beschäftigungs- und Work-Life-Balance-Möglichkeiten zu haben, und Jahre später bin ich fest davon überzeugt, dass dies die richtige Entscheidung war.<br /><br />&emsp;Ich habe das Gefühl, dass ich mich in einer fast einzigartigen Position befinde, da ich jetzt meine wissenschaftlichen und analytischen Fähigkeiten nutzen kann, um Websites (wie zum Beispiel mein CSS-Parsing-Tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) zu entwickeln, die andere Leute oder sogar Teams nicht kosteneffizient gestalten könnten produzieren, da für solche Standorte mehrere Mitarbeiter mit unterschiedlichen Fähigkeiten erforderlich wären. Die <a href="https://www.crystallography.net" target="_blank" rel="noreferrer">Offene Kristallographie-Datenbank</a> (COD) und die zugehörige RESTful-API bieten eine solche Möglichkeit. Diese Datenbank ist ein mutiger Versuch, wissenschaftliche Daten der Öffentlichkeit zugänglich zu machen. Allerdings führen die unerschwinglichen Kosten für die Einstellung eines teuren Entwicklers (wie mich) in Verbindung mit der Finanzierungslage in den chemischen Wissenschaften, soweit ich das beurteilen kann, zu offensichtlichen Lücken in der Struktur und dem Schema der API. Crystal Search ist ein Versuch, diese Anomalien zu berücksichtigen und außerdem „Mehrwert“-Filter zu integrieren, die die Suche nach COD wesentlich effizienter machen. Als zusätzlicher Bonus war dies für mich eine willkommene Gelegenheit, erneut an einem Projekt im Bereich der chemischen Wissenschaften zu arbeiten.'
  },
  en: {
    heading: 'About',
    content: 'My name is Dr. David Partyka, and I created Crystal Search. Although I was trained for several years as a chemist, and even earned a PhD from a top university and published over 20 papers, I transitioned into web development after the last engineering company I worked for (heavily-focused on chemistry) folded in 2011. I made this career transition for better employment and work-life balance opportunities, and years later, I wholeheartedly believe this was the correct choice.<br /><br />&emsp;I feel that I am in an almost unique position in that I can now use my scientific and analytical skills to develop websites (such as my CSS parsing tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) that other people, or even teams, would not be able to cost-efficiently produce because such sites would require multiple personnel with different skill sets. The <a href="https://www.crystallography.net" target="_blank" rel="noreferrer">Crystallography Open Database</a> (COD), and its associated RESTful API, present one such opportunity. This database is a valiant effort to make scientific data available to the public. However, the prohibitive cost of hiring an expensive developer (like me), combined with the state of funding in the chemical sciences, as far as I can tell, account for obvious gaps in the structure and schema of the API. Crystal Search is an effort to account for these anomalies, and also integrate "value-added" filters, that will make searching COD much more efficient. As an added bonus, this was a welcome opportunity for me to work - once again - on a chemical sciences related project.'
  },
  es: {
    heading: 'Acerca de',
    content: 'Mi nombre es Dr. David Partyka y creé Crystal Search. Aunque me formé como químico durante varios años, e incluso obtuve un doctorado de una de las mejores universidades y publiqué más de 20 artículos, hice la transición al desarrollo web después de que la última empresa de ingeniería para la que trabajé (muy centrada en la química) cerró en 2011. Hice esta transición profesional para obtener mejores oportunidades de empleo y equilibrio entre vida personal y laboral, y años después, creo sinceramente que esta fue la elección correcta.<br /><br />&emsp;Siento que estoy en una posición casi única en ese sentido. Ahora puedo utilizar mis habilidades científicas y analíticas para desarrollar sitios web (como mi herramienta de análisis de CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que otras personas, o incluso equipos, no podrían producir de manera rentable porque dichos sitios requerirían mucho personal con diferentes habilidades. La <a href="https://www.crystallography.net" target="_blank" rel="noreferrer">Base de datos Abierta de Cristalografía</a> (COD) y su API RESTful asociada presentan una de esas oportunidades. Esta base de datos es un esfuerzo valiente para poner los datos científicos a disposición del público. Sin embargo, el coste prohibitivo de contratar a un desarrollador caro (como yo), combinado con el estado de la financiación en las ciencias químicas, hasta donde yo sé, explica lagunas obvias en la estructura y el esquema de la API. Crystal Search es un esfuerzo por dar cuenta de estas anomalías y también integrar filtros de "valor agregado", que harán que la búsqueda COD sea mucho más eficiente. Como beneficio adicional, esta fue una buena oportunidad para mí de trabajar, una vez más, en un proyecto relacionado con las ciencias químicas.'
  },
  fr: {
    heading: 'À propos',
    content: 'Je m\'appelle le Dr David Partyka et j\'ai créé Crystal Search. Bien que j\'aie été formé pendant plusieurs années en tant que chimiste, et que j\'ai même obtenu un doctorat dans une grande université et publié plus de 20 articles, j\'ai fait la transition vers le développement Web après la fermeture de la dernière société d\'ingénierie pour laquelle j\'ai travaillé (fortement axée sur la chimie) en 2011. J\'ai fait cette transition de carrière pour de meilleures opportunités d\'emploi et d\'équilibre travail-vie personnelle, et des années plus tard, je crois de tout cœur que c\'était le bon choix.<br /><br />&emsp;Je sens que je suis dans une position presque unique dans ce domaine. Je peux désormais utiliser mes compétences scientifiques et analytiques pour développer des sites Web (comme mon outil d\'analyse CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que d\'autres personnes, ou même des équipes, ne seraient pas en mesure de produire de manière rentable car de tels sites nécessiteraient plusieurs personnes possédant des compétences différentes. La <a href="https://www.cristallography.net" target="_blank" rel="noreferrer">Base de données ouverte cristallographie</a> (COD) et son API RESTful associée présentent une telle opportunité. Cette base de données est un vaillant effort pour mettre les données scientifiques à la disposition du public. Cependant, le coût prohibitif de l\'embauche d\'un développeur coûteux (comme moi), combiné à l\'état du financement des sciences chimiques, pour autant que je sache, explique des lacunes évidentes dans la structure et le schéma de l\'API. Crystal Search est un effort pour tenir compte de ces anomalies, et également intégrer des filtres « à valeur ajoutée », qui rendront la recherche COD beaucoup plus efficace. En prime, c\'était pour moi une opportunité bienvenue de travailler - une fois de plus - sur un projet lié aux sciences chimiques.'
  },
  it: {
    heading: 'Di',
    content: 'Mi chiamo Dr. David Partyka e ho creato Crystal Search. Sebbene abbia studiato per diversi anni come chimico e abbia anche conseguito un dottorato di ricerca in una delle migliori università e pubblicato oltre 20 articoli, sono passato allo sviluppo web dopo che l\'ultima società di ingegneria per cui ho lavorato (fortemente focalizzata sulla chimica) ha chiuso i battenti nel 2011. Ho intrapreso questa transizione professionale per migliori opportunità di lavoro e di equilibrio tra lavoro e vita privata e, anni dopo, credo fermamente che questa sia stata la scelta corretta.<br /><br />&emsp;Sento di trovarmi in una posizione quasi unica in questo Ora posso utilizzare le mie capacità scientifiche e analitiche per sviluppare siti web (come il mio strumento di analisi CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) che altre persone, o addirittura team, non sarebbero in grado di produrre in modo economicamente efficiente perché tali siti richiederebbero più personale con competenze diverse. Il <a href="https://www.crystallography.net" target="_blank" rel="noreferrer">Database Aperto di Cristallografia</a> (COD) e la relativa API RESTful associata offrono una di queste opportunità. Questo database rappresenta uno sforzo coraggioso per rendere i dati scientifici disponibili al pubblico. Tuttavia, il costo proibitivo dell\'assunzione di uno sviluppatore costoso (come me), combinato con lo stato dei finanziamenti nelle scienze chimiche, per quanto ne so, spiegano evidenti lacune nella struttura e nello schema dell\'API. Crystal Search è uno sforzo per tenere conto di queste anomalie e anche per integrare filtri a "valore aggiunto", che renderanno la ricerca COD molto più efficiente. Come ulteriore vantaggio, questa è stata per me una gradita opportunità di lavorare, ancora una volta, su un progetto correlato alle scienze chimiche.'
  },
  ru: {
    heading: 'О',
    content: 'Меня зовут доктор Дэвид Партика, и я создал Crystal Search. Хотя я несколько лет учился на химика, даже получил докторскую степень в ведущем университете и опубликовал более 20 статей, я перешел в веб-разработку после того, как последняя инжиниринговая компания, в которой я работал (специально ориентированная на химию), закрылась в 2011 году. Я совершил этот карьерный переход, чтобы улучшить возможности трудоустройства и найти баланс между работой и личной жизнью, и спустя годы я искренне верю, что это был правильный выбор.<br /><br />&emspЯ чувствую, что нахожусь в почти уникальном положении: теперь я могу использовать свои научные и аналитические навыки для разработки веб-сайтов (например, мой инструмент анализа CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>), которые другие люди или даже команды не смогут создать экономически эффективно, поскольку такие сайты потребуют большого количества сотрудников с разными наборами навыков. <a href="https://www.crystallography.net" target="_blank" rel="noreferrer">Открытая база данных кристаллографии</a> (COD) и связанный с ней RESTful API предоставляют одну из таких возможностей. Эта база данных представляет собой отважную попытку сделать научные данные доступными для общественности. Однако непомерно высокая стоимость найма дорогого разработчика (такого, как я) в сочетании с состоянием финансирования химических наук, насколько я могу судить, объясняет очевидные пробелы в структуре и схеме API. Crystal Search — это попытка учесть эти аномалии, а также интегрировать дополнительные фильтры, которые сделают поиск COD намного более эффективным. В качестве дополнительного бонуса для меня это была долгожданная возможность снова поработать над проектом, связанным с химическими науками.'
  }
};

export default TEXT_MAP;
